# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrainingXLPagerTabStrip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrainingXLPagerTabStrip
  pod 'XLPagerTabStrip', '~> 9.0'
end
